---
- hosts: localhost

  roles:
    # setup the common environment files
    - role: '../dotfiles'

    # setup the homebrew, caskroom, gems configuration
    - role: osx.homebrew
      when: ansible_distribution == 'MacOSX'

  tasks:

    - meta: flush_handlers

    # install all Brew apps
    - name: copy over Brewfile
      copy: src=files/Brewfile dest=/tmp/Brewfile
      register: brewfile
      
    - name: install applications from Brewfile
      shell: brew brewdle chdir=/tmp/
      when: brewfile.changed

    # configure zsh
    - name: configure zsh, if installed
      stat: path=/usr/local/bin/zsh
      register: zsh_installed

    - name: add homebrew zsh to /etc/shells
      sudo: yes
      lineinfile: dest=/etc/shells
                  regexp="local"
                  line="/usr/local/bin/zsh"
                  state=present
      when: zsh_installed.stat.exists == true

    - name: set zsh as default shell
      shell: chsh -s /usr/local/bin/zsh
      when: zsh_installed.stat.exists == true

